- name: Demonstartes list and how to ilterate a loop user-defined variable
  hosts: localhost
  vars: 
   - my_softwares:
       - vim
       - tree
       - default-jdk
       - maven
       - ruby
  tasks: 
   - name: Install the software tool
     debug: msg="{{item}} utility."
     with_list: "{{my_softwares}}"
 
